import { execFileSync, spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { resolveOrigins, type SiteOrigins } from "../client/src/site-config.ts";

const SHA = /^[0-9a-f]{40}$/;
export const HEAD_MARKER = "<!--app-head-->";
export const HTML_MARKER = "<!--app-html-->";

export type BuildMeta = {
  release: string;
  builtAt: string;
  origins: SiteOrigins;
};

export type UiGap = { file: string; detail: string };

const uiFiles: { file: string; detail: string; includes?: string[] }[] = [
  {
    file: "client/index.html",
    detail: "keep <!--app-head-->, <!--app-html-->, and the /src/main.tsx script so the build can fill them in",
    includes: [HEAD_MARKER, HTML_MARKER, "/src/main.tsx"],
  },
  { file: "client/src/main.tsx", detail: "hydrate BrowserRouter and App with buildMeta.origins" },
  { file: "client/src/App.tsx", detail: "export function App({ origins }: { origins: SiteOrigins })" },
  {
    file: "client/src/entry-server.tsx",
    detail: "export render(url, origins) and re-export renderHead, robotsTxt, sitemapXml, llmsTxt, and prerenderRoutes",
  },
];

export function missingUi(root = process.cwd()): UiGap[] {
  const gaps: UiGap[] = [];
  for (const item of uiFiles) {
    const full = path.join(root, item.file);
    if (!fs.existsSync(full)) {
      gaps.push({ file: item.file, detail: item.detail });
      continue;
    }
    if (!item.includes) continue;
    const text = fs.readFileSync(full, "utf8");
    const absent = item.includes.filter((needle) => !text.includes(needle));
    if (absent.length) gaps.push({ file: item.file, detail: `missing ${absent.join(", ")}. ${item.detail}` });
  }
  return gaps;
}

export function resolveRelease(env: Record<string, string | undefined>, gitSha?: string): string {
  for (const key of ["VERCEL_GIT_COMMIT_SHA", "GITHUB_SHA"]) {
    const value = env[key]?.trim().toLowerCase();
    if (value && SHA.test(value)) return value;
  }
  const fromGit = gitSha?.trim().toLowerCase();
  if (fromGit && SHA.test(fromGit)) return fromGit;
  return "local";
}

export function renderBuildMetaSource(meta: BuildMeta): string {
  return `import type { SiteOrigins } from "../site-config";

/**
 * Regenerated by scripts/build.ts before the client bundle and the SSR bundle.
 * \`release\` is a 40-character git SHA, or \`local\` when no SHA is available.
 * It is not a secret.
 */
export const buildMeta: { release: string; builtAt: string; origins: SiteOrigins } = ${JSON.stringify(meta, null, 2)};

export const buildId = buildMeta.release;
`;
}

export function injectHtml(template: string, head: string, html: string): string {
  if (!template.includes(HEAD_MARKER) || !template.includes(HTML_MARKER)) {
    throw new Error("Built index.html is missing <!--app-head--> or <!--app-html-->. Leave both markers in client/index.html.");
  }
  const next = template.replace(HEAD_MARKER, () => head).replace(HTML_MARKER, () => html);
  if (next.includes(HEAD_MARKER) || next.includes(HTML_MARKER)) {
    throw new Error("The prerender markers were still in the page after injection.");
  }
  return next;
}

export function gitHead(): string | undefined {
  try {
    return execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return undefined;
  }
}

function run(command: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: "inherit" });
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`${command} ${args.join(" ")} exited ${code ?? "null"}`));
    });
  });
}

function findServerEntry(dir: string): string {
  const expected = path.join(dir, "entry-server.js");
  if (fs.existsSync(expected)) return expected;
  const found: string[] = [];
  const walk = (current: string) => {
    if (!fs.existsSync(current)) return;
    for (const name of fs.readdirSync(current)) {
      const full = path.join(current, name);
      if (fs.statSync(full).isDirectory()) walk(full);
      else if (name.endsWith(".js")) found.push(path.relative(dir, full));
    }
  };
  walk(dir);
  throw new Error(`SSR build did not emit dist/server/entry-server.js. Found: ${found.join(", ") || "nothing"}`);
}

type ServerEntry = {
  render: (url: string, origins: SiteOrigins) => string;
  renderHead: (route: { path: string }, origins: SiteOrigins) => string;
  robotsTxt: (origins: SiteOrigins) => string;
  sitemapXml: (origins: SiteOrigins) => string;
  llmsTxt: (origins: SiteOrigins) => string;
  prerenderRoutes: { path: string; outputFile: string; kind: string; inSitemap: boolean }[];
};

function assertEntry(value: Partial<ServerEntry>): ServerEntry {
  const names = ["render", "renderHead", "robotsTxt", "sitemapXml", "llmsTxt", "prerenderRoutes"] as const;
  const missing = names.filter((name) => value[name] === undefined);
  if (missing.length) {
    throw new Error(`dist/server/entry-server.js is missing: ${missing.join(", ")}`);
  }
  return value as ServerEntry;
}

function isDirectRun(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  return path.resolve(entry) === path.resolve(fileURLToPath(import.meta.url));
}

async function main(): Promise<void> {
  const gaps = missingUi();
  if (gaps.length) {
    console.error("The interface files are not in this checkout yet, so there is nothing to prerender.");
    for (const gap of gaps) console.error(`- ${gap.file}: ${gap.detail}`);
    console.error("Build order once those files exist: write build-meta.ts, Vite client, Vite SSR, then HTML for every route and 404.");
    process.exit(1);
  }

  const release = resolveRelease(process.env, gitHead());
  const meta: BuildMeta = {
    release,
    builtAt: new Date().toISOString(),
    origins: resolveOrigins(process.env),
  };
  const metaFile = path.join("client/src/generated/build-meta.ts");
  fs.writeFileSync(metaFile, renderBuildMetaSource(meta));

  const viteBin = path.resolve("node_modules/vite/bin/vite.js");
  await run(process.execPath, [viteBin, "build"]);
  await run(process.execPath, [viteBin, "build", "--ssr", "src/entry-server.tsx"]);

  const serverFile = findServerEntry(path.resolve("dist/server"));
  const entry = assertEntry((await import(pathToFileURL(serverFile).href)) as Partial<ServerEntry>);
  const templatePath = path.resolve("dist/public/index.html");
  const template = fs.readFileSync(templatePath, "utf8");
  const publicDir = path.resolve("dist/public");

  for (const route of entry.prerenderRoutes) {
    const head = entry.renderHead(route, meta.origins);
    const html = entry.render(route.path, meta.origins);
    if (typeof head !== "string" || typeof html !== "string") {
      throw new Error(`render or renderHead did not return a string for ${route.path}`);
    }
    const page = injectHtml(template, head, html);
    const dest = path.join(publicDir, route.outputFile);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, page);
  }

  fs.writeFileSync(path.join(publicDir, "robots.txt"), entry.robotsTxt(meta.origins));
  fs.writeFileSync(path.join(publicDir, "sitemap.xml"), entry.sitemapXml(meta.origins));
  fs.writeFileSync(path.join(publicDir, "llms.txt"), entry.llmsTxt(meta.origins));
  const receipt = {
    release: meta.release,
    builtAt: meta.builtAt,
    indexable: meta.origins.indexable,
    canonicalOrigin: meta.origins.canonicalOrigin,
  };
  fs.writeFileSync(path.join(publicDir, "version.json"), `${JSON.stringify(receipt, null, 2)}\n`);
  fs.mkdirSync(path.resolve("dist"), { recursive: true });
  fs.writeFileSync(
    path.resolve("dist/route-manifest.json"),
    `${JSON.stringify(
      entry.prerenderRoutes.map((route) => ({
        path: route.path,
        outputFile: route.outputFile,
        kind: route.kind,
        inSitemap: route.inSitemap,
      })),
      null,
      2,
    )}\n`,
  );
  console.log(`Prerendered ${entry.prerenderRoutes.length} pages. Release ${meta.release}.`);
}

if (isDirectRun()) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
